# Generated by Django 2.2 on 2019-04-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Джедай',
                'verbose_name_plural': 'Джедаи',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название планеты')),
            ],
            options={
                'verbose_name': 'Планета',
                'verbose_name_plural': 'Планеты',
            },
        ),
        migrations.CreateModel(
            name='Padawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('result_test', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Результат Теста')),
                ('jedi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='padawan_jedi', to='profiles.Jedi', verbose_name='Джедай')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='padawan_planet', to='profiles.Planet', verbose_name='Планета')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_planet', to='profiles.Planet', verbose_name='Планета')),
            ],
            options={
                'verbose_name': 'Ордин',
                'verbose_name_plural': 'Ордин',
            },
        ),
        migrations.AddField(
            model_name='jedi',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jedi_order', to='profiles.Order', verbose_name='Ордин'),
        ),
    ]
