# Generated by Django 2.2 on 2019-04-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='planet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_planet', to='profiles.Planet', verbose_name='Планета'),
        ),
    ]
