# Generated by Django 2.2 on 2019-04-20 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190419_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='planet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_planet', to='profiles.Planet', verbose_name='Планета'),
        ),
        migrations.AlterField(
            model_name='padawan',
            name='jedi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padawan_jedi', to='profiles.Jedi', verbose_name='Джедай'),
        ),
    ]
