# Generated by Django 2.2 on 2019-04-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='planet',
        ),
    ]
