# Generated by Django 2.2 on 2019-04-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_test_planet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='order_id',
            new_name='order',
        ),
    ]
